### ISSUE TITLE
Docker registry does not work with autoscaled agents

### ISSUE THREAD

**Issue by AmalQB** [microservices-today/IaC-dcos-docker-registry#14]
The new autoscaled agents will miss the openssl certificates generated for docker daemon.

**Comment by alexraju** [comment]
New agents will pull openssl certificates from bootstrap node. 
Fixed with https://github.com/microservices-today/IaC-dcos-docker-registry/pull/19 and https://github.com/microservices-today/IaC-dcos/pull/56
